### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by yoonhakcher** [opteroncx/MoePhoto#29]
Windows 10 18363.476
```
Active code page: 65001
Active code page: 65001
E:\Tools\萌图工具箱4.6.3\lib\torch\cuda\__init__.py:117: UserWarning:
    Found GPU0 GeForce GTX 660 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.

Current working directory: E:\Tools\萌图工具箱4.6.3
Server starts to listen on http://127.0.0.1:2333/, press Ctrl+C to exit.
127.0.0.1 - - [2019-11-22 20:17:38] "GET /msg?session=&path=%2Fimage_enhance&_=1574421458707 HTTP/1.1" 403 138 0.000000
127.0.0.1 - - [2019-11-22 20:17:42] "GET / HTTP/1.1" 200 8602 0.000000
127.0.0.1 - - [2019-11-22 20:17:42] "GET /static/fonts/037d830416495def72b7881024c14b7b.woff2 HTTP/1.1" 200 15745 0.296872
127.0.0.1 - - [2019-11-22 20:17:42] "GET /static/images/img1.jpg HTTP/1.1" 304 206 0.000000
127.0.0.1 - - [2019-11-22 20:17:42] "GET /static/js/30fe1313c8b4a05021c1.js HTTP/1.1" 304 210 0.000000
127.0.0.1 - - [2019-11-22 20:17:42] "GET /static/js/602aff685874b0468060.js HTTP/1.1" 304 211 0.015625
127.0.0.1 - - [2019-11-22 20:17:42] "GET /static/js/main.js HTTP/1.1" 304 211 0.000000
127.0.0.1 - - [2019-11-22 20:17:42] "GET /static/images/a1.png HTTP/1.1" 200 77351 0.000000
127.0.0.1 - - [2019-11-22 20:17:42] "GET /static/images/img2.jpg HTTP/1.1" 304 206 0.000000
127.0.0.1 - - [2019-11-22 20:17:42] "GET /static/css/styles.fbb53c7f2bc5fa4ad0dc.css HTTP/1.1" 200 231212 0.000000
127.0.0.1 - - [2019-11-22 20:17:42] "GET /static/js/278271f557a037509530.js HTTP/1.1" 304 210 0.000000
127.0.0.1 - - [2019-11-22 20:17:43] "GET /msg?session=1574421462.608274&path=%2Fimage_enhance&_=1574421462992 HTTP/1.1" 200 115 0.000000
127.0.0.1 - - [2019-11-22 20:17:43] "GET /static/bg/76d472a01dea4878e2039c37e983a3a0.png HTTP/1.1" 304 213 0.000000
127.0.0.1 - - [2019-11-22 20:17:43] "GET /msg?session=1574421462.608274&_=1574421462993 HTTP/1.1" 200 115 0.015625
127.0.0.1 - - [2019-11-22 20:17:43] "GET /favicon.ico HTTP/1.1" 404 109 0.015625
127.0.0.1 - - [2019-11-22 20:18:07] "GET /preset?path=image HTTP/1.1" 200 117 0.000000
127.0.0.1 - - [2019-11-22 20:18:15] "POST /preset?path=image HTTP/1.1" 200 118 0.000000
127.0.0.1 - - [2019-11-22 20:18:33] "GET /msg?session=1574421462.608274&path=%2Fimage_enhance&_=1574421462994 HTTP/1.1" 200 115 0.000000
2019-11-22 11:18:33.346|Moe|loading model ./model/dn_lite5/model_new.pth
2019-11-22 11:18:33.361|Moe|reloading weights
E:\Tools\萌图工具箱4.6.3\lib\torch\cuda\__init__.py:117: UserWarning:
    Found GPU0 GeForce GTX 660 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.

127.0.0.1 - - [2019-11-22 20:18:33] "GET /msg?session=1574421462.608274&path=%2Fimage_enhance&_=1574421462996 HTTP/1.1" 200 152 0.203111
127.0.0.1 - - [2019-11-22 20:18:33] "GET /msg?session=1574421462.608274&_=1574421462995 HTTP/1.1" 200 159 0.234361
THCudaCheck FAIL file=c:\a\w\1\s\windows\pytorch\aten\src\thcunn\generic/SpatialReflecti127.0.0.1 - - [2019-11-22 20:18:33] "GET /msg?session=1574421462.608274&_=1574421462997 HTTP/1.1" 200 153 0.000000
onPadding.cu line=74 error=48 : no kernel image is available for execution on the device
2019-11-22 11:18:33.658|Moe|ERROR   |worker:56|['imageEnhance', 949852, {'model': 'lite5', 'op': 'DN'}]
Traceback (most recent call last):
  File "./python/worker.py", line 53, in g
  File "./python/MoePhoto.py", line 40, in imageEnhance
  File "./python/progress.py", line 164, in g
  File "./python/imageProcess.py", line 404, in <lambda>
  File "./python/imageProcess.py", line 380, in <lambda>
  File "./python/imageProcess.py", line 253, in <lambda>
  File "./python/imageProcess.py", line 249, in <lambda>
  File "./python/progress.py", line 164, in g
  File "./python/imageProcess.py", line 301, in <lambda>
  File "./python/runDN.py", line 18, in <lambda>
  File "./python/imageProcess.py", line 261, in <lambda>
  File "./python/imageProcess.py", line 36, in doCrop
  File "C:\Users\opteroncx.000\Py36\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
  File "C:\Users\opteroncx.000\Py36\lib\site-packages\torch\nn\modules\padding.py", line 172, in forward
  File "C:\Users\opteroncx.000\Py36\lib\site-packages\torch\nn\functional.py", line 2685, in pad
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at c:\a\w\1\s\windows\pytorch\aten\src\thcunn\generic/SpatialReflectionPadding.cu:74
127.0.0.1 - - [2019-11-22 20:18:33] "POST /image_enhance?session=1574421462.608274 HTTP/1.1" 200 115 0.374985
127.0.0.1 - - [2019-11-22 20:18:33] "GET /msg?session=1574421462.608274&_=1574421462998 HTTP/1.1" 200 115 0.000000
127.0.0.1 - - [2019-11-22 20:18:33] "GET /msg?session=1574421462.608274&_=1574421462999 HTTP/1.1" 200 115 0.000000
127.0.0.1 - - [2019-11-22 20:18:33] "GET /msg?session=1574421462.608274&_=1574421463000 HTTP/1.1" 200 115 0.000000
127.0.0.1 - - [2019-11-22 20:18:33] "GET /msg?session=1574421462.608274&path=%2Fimage_enhance&_=1574421463001 HTTP/1.1" 400 1402 0.000000
127.0.0.1 - - [2019-11-22 20:18:33] "GET /msg?session=1574421462.608274&_=1574421463002 HTTP/1.1" 200 115 0.000000
127.0.0.1 - - [2019-11-22 20:18:38] "GET /msg?session=1574421462.608274&path=%2Fimage_enhance&_=1574421463003 HTTP/1.1" 200 115 0.000000
127.0.0.1 - - [2019-11-22 20:18:39] "GET /msg?session=1574421462.608274&_=1574421463004 HTTP/1.1" 200 115 0.000000
```

**Comment by opteroncx** [comment]
换显卡，你的显卡太老了不支持cuda10

**Comment by opteroncx** [comment]
或者你下载这里的源码，然后自行安装Python环境（推荐anaconda），然后安装cuda8，以及支持cuda8的老版本pytorch（0.4.0）

**Comment by yoonhakcher** [comment]
@opteroncx 
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89
```
